### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by unverciftci** [ROBOTIS-JAPAN-GIT/dynamixel_mikata_arm#2]
Hi,
It's a great project. Do you have an English documentation, please? Especially for the hardware installation. Thank you.
Unver

**Comment by t-kitajima** [comment]
Hi,
There is a project that Mikata Arm is following.
Since there is an English document here, please refer to that.
[https://github.com/ROBOTIS-GIT/open_manipulator](https://github.com/ROBOTIS-GIT/open_manipulator)
