### ISSUE TITLE
インストールスクリプトでエラーが出る

### ISSUE THREAD

**Issue by eibow1012** [ROBOTIS-JAPAN-GIT/dynamixel_mikata_arm#3]
インストールスクリプトでエラーが出ます。MIKATA_armの実機のIDは１１から１５になっていますが、以下のエラーはIDが１から５になっています。なぜ、このようなエラーが出るのかわかりません。教えていただけませんか。
設定ファイルが存在するならどれになりますか。

eibow@Alienware-17-R5:~/catkin_ws$ ./src/dynamixel_mikata_arm/install.sh
Suceeded to open the port
Succeeded to change the baudrate
ERROR: Could not connect to ID 1
ERROR: Could not connect to ID 2
ERROR: Could not connect to ID 3
ERROR: Could not connect to ID 4
ERROR: Could not connect to ID 5
DXL_setup_mikata_arm_position_control_mode
checking the DXLs settings.
  current_DXL_settings
[TxRxResult] There is no status packet!
terminate called after throwing an instance of 'std::runtime_error'
  what():  SyncRead Fail
./src/dynamixel_mikata_arm/install.sh: 25 行:  8535 中止                  (コアダンプ) rosrun mikata_arm_toolbox dxl_setup

**Comment by Affonso-Gui** [comment]
こんにちは、

このリポジトリでは実機のIDが１から５になっていることを想定しています。そのように変更すれば、問題なく動くと思います。

> 各モーターのIDはベースリンク(基台取り付け側)から順に1から5を前提としています。(README.md)

Dynamixelと通信を開始するためにはbaudrateとIDの両方を指定する必要があるので、以上のようなエラーが出るのは `プログラムがID 1~5 との通信を開始しようとしたのだが、そのIDが見つからず通信が成立しない` という状況になったからです。

ちなみに設定ファイルは [dxl_setup](https://github.com/ROBOTIS-JAPAN-GIT/dynamixel_mikata_arm/blob/master/mikata_arm_toolbox/src/dxl_setup.cpp) で、`install.sh`の中で実行されています。

**Comment by t-kitajima** [comment]
しばらくの間、アクションが無かったため問題が解決されたと考えcloseにします。
何かあれば、再度このIssueeをopenしてください。
